"""service

Revision ID: 6f587c2cbc73
Revises: f68ba34aa00f
Create Date: 2025-05-21 13:03:16.732649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.service import service_status_sql_enum

# revision identifiers, used by Alembic.
revision: str = '6f587c2cbc73'
down_revision: Union[str, None] = 'f68ba34aa00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    service_status_sql_enum.create(op.get_bind(), checkfirst=False)

    op.add_column('tbl_category', sa.Column('available', sa.Boolean(), nullable=False))
    op.add_column('tbl_service', sa.Column('status', service_status_sql_enum, nullable=True))
    op.add_column('tbl_service', sa.Column('requested_user_id', sa.Integer(), nullable=False))
    op.alter_column('tbl_service', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key('tbl_service_requested_user_id_fkey', 'tbl_service', 'tbl_user', ['requested_user_id'], ['id'])
    op.drop_column('tbl_service', 'available')
    op.drop_column('tbl_service', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_service', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tbl_service', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('tbl_service_requested_user_id_fkey', 'tbl_service', type_='foreignkey')
    op.alter_column('tbl_service', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tbl_service', 'requested_user_id')
    op.drop_column('tbl_service', 'status')
    op.drop_column('tbl_category', 'available')
    
    service_status_sql_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
