"""initial_tables

Revision ID: f68ba34aa00f
Revises: 
Create Date: 2025-05-17 13:43:18.967096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.service import category_type_sql_enum, RSVP_status_sql_enum, help_request_status_sql_enum, reminder_type_sql_enum

# revision identifiers, used by Alembic.
revision: str = 'f68ba34aa00f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_country_id'), 'tbl_country', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_country_name'), 'tbl_country', ['name'], unique=False)
    op.create_table('tbl_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_role_id'), 'tbl_role', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_role_name'), 'tbl_role', ['name'], unique=False)
    op.create_table('tbl_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_state_id'), 'tbl_state', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_state_name'), 'tbl_state', ['name'], unique=False)
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile_code', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('otp', sa.BigInteger(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_email'), 'tbl_user', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_user_id'), 'tbl_user', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_mobile_number'), 'tbl_user', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_tbl_user_name'), 'tbl_user', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_user_role_id'), 'tbl_user', ['role_id'], unique=False)
    op.create_table('tbl_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', category_type_sql_enum , nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_category_created_by'), 'tbl_category', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_category_id'), 'tbl_category', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_category_name'), 'tbl_category', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_category_updated_by'), 'tbl_category', ['updated_by'], unique=False)
    op.create_table('tbl_district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_district_id'), 'tbl_district', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_district_name'), 'tbl_district', ['name'], unique=False)
    op.create_table('tbl_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_event_created_by'), 'tbl_event', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_event_id'), 'tbl_event', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_event_title'), 'tbl_event', ['title'], unique=False)
    op.create_index(op.f('ix_tbl_event_updated_by'), 'tbl_event', ['updated_by'], unique=False)
    op.create_table('tbl_meeting_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['tbl_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_meeting_log_id'), 'tbl_meeting_log', ['id'], unique=False)
    op.create_table('tbl_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_notification_id'), 'tbl_notification', ['id'], unique=False)
    op.create_table('tbl_event_rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', RSVP_status_sql_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['tbl_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_event_rsvp_id'), 'tbl_event_rsvp', ['id'], unique=False)
    op.create_table('tbl_help_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', help_request_status_sql_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('request_closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['tbl_user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_help_request_id'), 'tbl_help_request', ['id'], unique=False)
    op.create_table('tbl_notification_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', reminder_type_sql_enum, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_status', sa.Boolean(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['tbl_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_notification_reminder_id'), 'tbl_notification_reminder', ['id'], unique=False)
    op.create_table('tbl_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_service_category_id'), 'tbl_service', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_service_created_by'), 'tbl_service', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_service_id'), 'tbl_service', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_service_updated_by'), 'tbl_service', ['updated_by'], unique=False)
    op.create_table('tbl_user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('native_address_line', sa.Text(), nullable=True),
    sa.Column('native_district_id', sa.Integer(), nullable=True),
    sa.Column('native_state_id', sa.Integer(), nullable=True),
    sa.Column('native_country_id', sa.Integer(), nullable=True),
    sa.Column('current_address_line', sa.Text(), nullable=False),
    sa.Column('current_district_id', sa.Integer(), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=False),
    sa.Column('current_country_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('language_pref', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_country_id'], ['tbl_country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_district_id'], ['tbl_district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_state_id'], ['tbl_state.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['native_country_id'], ['tbl_country.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['native_district_id'], ['tbl_district.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['native_state_id'], ['tbl_state.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_profile_aadhaar_number'), 'tbl_user_profile', ['aadhaar_number'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_created_by'), 'tbl_user_profile', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_current_address_line'), 'tbl_user_profile', ['current_address_line'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_current_country_id'), 'tbl_user_profile', ['current_country_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_current_district_id'), 'tbl_user_profile', ['current_district_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_current_state_id'), 'tbl_user_profile', ['current_state_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_id'), 'tbl_user_profile', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_native_address_line'), 'tbl_user_profile', ['native_address_line'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_native_country_id'), 'tbl_user_profile', ['native_country_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_native_district_id'), 'tbl_user_profile', ['native_district_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_native_state_id'), 'tbl_user_profile', ['native_state_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_profile_updated_by'), 'tbl_user_profile', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_profile_updated_by'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_native_state_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_native_district_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_native_country_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_native_address_line'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_current_state_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_current_district_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_current_country_id'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_current_address_line'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_created_by'), table_name='tbl_user_profile')
    op.drop_index(op.f('ix_tbl_user_profile_aadhaar_number'), table_name='tbl_user_profile')
    op.drop_table('tbl_user_profile')
    op.drop_index(op.f('ix_tbl_service_updated_by'), table_name='tbl_service')
    op.drop_index(op.f('ix_tbl_service_id'), table_name='tbl_service')
    op.drop_index(op.f('ix_tbl_service_created_by'), table_name='tbl_service')
    op.drop_index(op.f('ix_tbl_service_category_id'), table_name='tbl_service')
    op.drop_table('tbl_service')
    op.drop_index(op.f('ix_tbl_notification_reminder_id'), table_name='tbl_notification_reminder')
    op.drop_table('tbl_notification_reminder')
    op.drop_index(op.f('ix_tbl_help_request_id'), table_name='tbl_help_request')
    op.drop_table('tbl_help_request')
    op.drop_index(op.f('ix_tbl_event_rsvp_id'), table_name='tbl_event_rsvp')
    op.drop_table('tbl_event_rsvp')
    op.drop_index(op.f('ix_tbl_notification_id'), table_name='tbl_notification')
    op.drop_table('tbl_notification')
    op.drop_index(op.f('ix_tbl_meeting_log_id'), table_name='tbl_meeting_log')
    op.drop_table('tbl_meeting_log')
    op.drop_index(op.f('ix_tbl_event_updated_by'), table_name='tbl_event')
    op.drop_index(op.f('ix_tbl_event_title'), table_name='tbl_event')
    op.drop_index(op.f('ix_tbl_event_id'), table_name='tbl_event')
    op.drop_index(op.f('ix_tbl_event_created_by'), table_name='tbl_event')
    op.drop_table('tbl_event')
    op.drop_index(op.f('ix_tbl_district_name'), table_name='tbl_district')
    op.drop_index(op.f('ix_tbl_district_id'), table_name='tbl_district')
    op.drop_table('tbl_district')
    op.drop_index(op.f('ix_tbl_category_updated_by'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_name'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_id'), table_name='tbl_category')
    op.drop_index(op.f('ix_tbl_category_created_by'), table_name='tbl_category')
    op.drop_table('tbl_category')
    op.drop_index(op.f('ix_tbl_user_role_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_name'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_mobile_number'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_id'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_email'), table_name='tbl_user')
    op.drop_table('tbl_user')
    op.drop_index(op.f('ix_tbl_state_name'), table_name='tbl_state')
    op.drop_index(op.f('ix_tbl_state_id'), table_name='tbl_state')
    op.drop_table('tbl_state')
    op.drop_index(op.f('ix_tbl_role_name'), table_name='tbl_role')
    op.drop_index(op.f('ix_tbl_role_id'), table_name='tbl_role')
    op.drop_table('tbl_role')
    op.drop_index(op.f('ix_tbl_country_name'), table_name='tbl_country')
    op.drop_index(op.f('ix_tbl_country_id'), table_name='tbl_country')
    op.drop_table('tbl_country')

    category_type_sql_enum.drop(op.get_bind(), checkfirst=True)
    RSVP_status_sql_enum.drop(op.get_bind(), checkfirst=True)
    help_request_status_sql_enum.drop(op.get_bind(), checkfirst=True)
    reminder_type_sql_enum.drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###
