"""update_on_delete

Revision ID: 43756aeb2adb
Revises: 6f587c2cbc73
Create Date: 2025-05-21 17:24:32.522888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43756aeb2adb'
down_revision: Union[str, None] = '6f587c2cbc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_event_rsvp_event_id_fkey', 'tbl_event_rsvp', type_='foreignkey')
    op.drop_constraint('tbl_event_rsvp_user_id_fkey', 'tbl_event_rsvp', type_='foreignkey')
    op.create_foreign_key("tbl_event_rsvp_event_id_fkey", 'tbl_event_rsvp', 'tbl_event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_event_rsvp_user_id_fkey', 'tbl_event_rsvp', 'tbl_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tbl_help_request_category_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.drop_constraint('tbl_help_request_assigned_staff_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.drop_constraint('tbl_help_request_user_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.create_foreign_key('tbl_help_request_category_id_fkey', 'tbl_help_request', 'tbl_category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_help_request_user_id_fkey', 'tbl_help_request', 'tbl_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_help_request_assigned_staff_id_fkey', 'tbl_help_request', 'tbl_user', ['assigned_staff_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tbl_meeting_log_admin_id_fkey', 'tbl_meeting_log', type_='foreignkey')
    op.drop_constraint('tbl_meeting_log_user_id_fkey', 'tbl_meeting_log', type_='foreignkey')
    op.create_foreign_key('tbl_meeting_log_admin_id_fkey', 'tbl_meeting_log', 'tbl_user', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tbl_meeting_log_user_id_fkey', 'tbl_meeting_log', 'tbl_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tbl_notification_user_id_fkey', 'tbl_notification', type_='foreignkey')
    op.create_foreign_key('tbl_notification_user_id_fkey', 'tbl_notification', 'tbl_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tbl_notification_reminder_event_id_fkey', 'tbl_notification_reminder', type_='foreignkey')
    op.create_foreign_key('tbl_notification_reminder_event_id_fkey', 'tbl_notification_reminder', 'tbl_event', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tbl_service_category_id_fkey', 'tbl_service', type_='foreignkey')
    op.create_foreign_key('tbl_service_category_id_fkey', 'tbl_service', 'tbl_category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_service_category_id_fkey', 'tbl_service', type_='foreignkey')
    op.create_foreign_key('tbl_service_category_id_fkey', 'tbl_service', 'tbl_category', ['category_id'], ['id'])
    op.drop_constraint('tbl_notification_reminder_event_id_fkey', 'tbl_notification_reminder', type_='foreignkey')
    op.create_foreign_key('tbl_notification_reminder_event_id_fkey', 'tbl_notification_reminder', 'tbl_event', ['event_id'], ['id'])
    op.drop_constraint('tbl_notification_user_id_fkey', 'tbl_notification', type_='foreignkey')
    op.create_foreign_key('tbl_notification_user_id_fkey', 'tbl_notification', 'tbl_user', ['user_id'], ['id'])
    op.drop_constraint('tbl_meeting_log_user_id_fkey', 'tbl_meeting_log', type_='foreignkey')
    op.drop_constraint('tbl_meeting_log_admin_id_fkey', 'tbl_meeting_log', type_='foreignkey')
    op.create_foreign_key('tbl_meeting_log_user_id_fkey', 'tbl_meeting_log', 'tbl_user', ['user_id'], ['id'])
    op.create_foreign_key('tbl_meeting_log_admin_id_fkey', 'tbl_meeting_log', 'tbl_user', ['admin_id'], ['id'])
    op.drop_constraint('tbl_help_request_assigned_staff_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.drop_constraint('tbl_help_request_user_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.drop_constraint('tbl_help_request_category_id_fkey', 'tbl_help_request', type_='foreignkey')
    op.create_foreign_key('tbl_help_request_user_id_fkey', 'tbl_help_request', 'tbl_user', ['user_id'], ['id'])
    op.create_foreign_key('tbl_help_request_assigned_staff_id_fkey', 'tbl_help_request', 'tbl_user', ['assigned_staff_id'], ['id'])
    op.create_foreign_key('tbl_help_request_category_id_fkey', 'tbl_help_request', 'tbl_category', ['category_id'], ['id'])
    op.drop_constraint('tbl_event_rsvp_user_id_fkey', 'tbl_event_rsvp', type_='foreignkey')
    op.drop_constraint("tbl_event_rsvp_event_id_fkey", 'tbl_event_rsvp', type_='foreignkey')
    op.create_foreign_key('tbl_event_rsvp_user_id_fkey', 'tbl_event_rsvp', 'tbl_user', ['user_id'], ['id'])
    op.create_foreign_key('tbl_event_rsvp_event_id_fkey', 'tbl_event_rsvp', 'tbl_event', ['event_id'], ['id'])
    # ### end Alembic commands ###
